--------------------------------------------------------
--  파일이 생성됨 - 금요일-10월-06-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EC_CHARGE
--------------------------------------------------------

  CREATE TABLE "CODETRAFFIC"."EC_CHARGE" 
   (	"EC_CITY" VARCHAR2(100 BYTE), 
	"EC_CHARGE" VARCHAR2(300 BYTE), 
	"EC_CHARGE_ID" NUMBER(38,0), 
	"EC_CHARGE_TYPE" VARCHAR2(100 BYTE), 
	"EC_CHARGE_FACILITY" VARCHAR2(100 BYTE), 
	"EC_CHARGE_PARKING" VARCHAR2(100 BYTE), 
	"EC_LOCATION" VARCHAR2(26 BYTE), 
	"EC_STATE" VARCHAR2(100 BYTE), 
	"EC_ADDRESS" VARCHAR2(500 BYTE), 
	"EC_TIME" VARCHAR2(300 BYTE), 
	"EC_USER" VARCHAR2(200 BYTE), 
	"EC_KW" VARCHAR2(100 BYTE), 
	"EC_FACILITY2" VARCHAR2(26 BYTE), 
	"EC_NOTE" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CODETRAFFIC.EC_CHARGE
SET DEFINE OFF;
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','SK허브수 인근 거주자우선주차장',2,'AC완속','주차시설','공영주차장','서울특별시','구로구','서울특별시 구로구 구일로10길 27(구로동, SK허브수) 지상1층 A동 앞 노상공영주차장','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','가산 공영주차장',1,'DC콤보','주차시설','공영주차장','서울특별시','금천구','서울특별시 금천구 시흥대로153길 53(가산동, 가산공영주차장) 지상 3층 옥상 진입로 왼쪽 10M','주중 08:00~19:00, 주말 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','강남구 압구정동 토끼굴 앞 가로등형 충전기',1,'DC콤보','주차시설','일반주차장','서울특별시','강남구','서울특별시 강남구 압구정로 321(서울특별시 강남구 선릉로189길 2 전기차충전소)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','개화산역 공영주차장',1,'DC콤보','주차시설','공영주차장','서울특별시','강서구','서울특별시 강서구 양천로 22(서울특별시 강서구 양천로16-1 전기차충전소)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','광진구 자양동 거주자우선주차장 가로등형 충전기',1,'DC콤보','주차시설','공영주차장','서울특별시','광진구','서울특별시 광진구 자양번영로3길 65(서울특별시 광진구 뚝섬로36길 39 전기차충전소)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','교통공원길 공영주차장 전기차 충전소',2,'AC완속','주차시설','공영주차장','서울특별시','송파구','서울특별시 송파구 신천동 10-2','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','기업은행 무교지점 앞 가로등형 충전소',1,'DC콤보','주차시설','일반주차장','서울특별시','중구','서울특별시 중구 무교로 20전기차충전소','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','남부초 공영주차장',1,'DC콤보','주차시설','공영주차장','서울특별시','관악구','서울특별시 관악구 남부순환로163길 14지하 1층 진입로 오른쪽 맨끝','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','남산청사',2,'AC완속','공공시설','지자체시설','서울특별시','중구','서울특별시 중구 삼일대로 231(예장동, 남산별관) 중부공원여가센터 앞 왼쪽 차단기 뒷편','평일 09:00~18:00',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','도곡정보문화도서관',2,'AC완속','공공시설','주민센터','서울특별시','강남구','서울특별시 강남구 도곡로18길 57(도곡동, 도곡정보문화도서관) 지상1층 정문 뒷편주차장','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','동작구청',1,'DC차데모+AC3상+DC콤보','공공시설','관공서','서울특별시','동작구','서울특별시 동작구 장승배기로 161전기차충전소','평일 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','동작구청 후문 가로등형 충전소',1,'DC콤보','주차시설','공영주차장','서울특별시','동작구','서울특별시 동작구 장승배기로 161(서울특별시 동작구 노량진로 8길 65 전기차충전소)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','드림디포 앞 가로등형 충전소',1,'DC콤보','주차시설','공영주차장','서울특별시','마포구','서울특별시 마포구 토정로 271전기차충전소','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','마곡중앙광장공영주차장',5,'DC콤보','주차시설','공영주차장','서울특별시','강서구','서울특별시 강서구 마곡중앙5로 지하9(마곡동, 마곡중앙광장) 공영주차장 지하2층 진입로 왼쪽 맨끝','24시간',null,'40kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','망우제2 거주자주차장',1,'DC콤보','주차시설','일반주차장','서울특별시','중랑구','서울특별시 중랑구 망우로71길 53(서울특별시 중랑구 송림길 82 전기차충전소)','주중 08:00~19:00, 주말 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','문정1동 주민센터 앞 전기차 충전소',1,'AC완속','주차시설','공영주차장','서울특별시','송파구','서울특별시 송파구 동남로 116(29-21 문정1동주민센터)','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','문정동 세광교회 앞 전기차 충전소',1,'AC완속','주차시설','공영주차장','서울특별시','송파구','서울특별시 송파구 동남로4길 37세광교회 앞(문정동 빌딩)','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','미아동 도봉세무서 앞 전기차 충전소',1,'AC완속','주차시설','공영주차장','서울특별시','강북구','서울특별시 강북구 도봉로 117(327-5 도봉세무서)','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','미아동 축산농협 전기차 충전소',2,'AC완속','주차시설','공영주차장','서울특별시','강북구','서울특별시 강북구 도봉로 136(131-30 풍양빌딩)','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','반포복개천 노상공영주차장',1,'DC콤보','주차시설','공영주차장','서울특별시','서초구','서울특별시 서초구 고무래로 35-2반포복개천 노상공영주차장(120-1 구두수선대)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','복정역 공영주차장',2,'DC콤보','주차시설','공영주차장','서울특별시','송파구','서울특별시 송파구 송파대로 지하6(서울특별시 송파구 성남대로 1564 전기차충전소)','주중 08:00~19:00, 주말 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','북가좌동 공영주차장 전기차 충전소',1,'AC완속','주차시설','공영주차장','서울특별시','서대문구','서울특별시 서대문구 거북골로14길 86거주자우선공영주차장(북가좌동 73-15)','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서대문구청 주차장',1,'DC콤보','공공시설','관공서','서울특별시','서대문구','서울특별시 서대문구 연희로 248전기차충전소','평일 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서소문청사(급속)',2,'DC콤보','공공시설','관공서','서울특별시','중구','서울특별시 중구 덕수궁길 15(서소문동, 서소문청사) 지상1층 진입로 오른쪽 5M 지점','평일 09:00~18:00',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서소문청사(완속)',3,'AC완속','공공시설','관공서','서울특별시','중구','서울특별시 중구 덕수궁길 15(서소문동, 서소문청사) 지상1층 진입로 오른쪽 5M 지점','주중 08:00~19:00, 주말 09:00~18:00',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서소문청사(지하주차장)',1,'DC콤보','공공시설','관공서','서울특별시','중구','서울특별시 중구 덕수궁길 15(서소문동, 서소문별관) 지하 진입로 직진 20M 지점','주중 08:00~19:00, 주말 09:00~18:00',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서소문청사(지하주차장)',2,'DC콤보','공공시설','관공서','서울특별시','중구','서울특별시 중구 덕수궁길 15(서소문동, 서소문별관) 지하 진입로 직진 20M 지점','주중 08:00~19:00, 주말 09:00~18:00',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서소문청사(후생동)',1,'AC완속','공공시설','관공서','서울특별시','중구','서울특별시 중구 덕수궁길 15(서소문동, 서소문청사후생동) 지상1층 주차장','주중 08:00~19:00, 주말 09:00~18:00',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서울시 본관청사',2,'AC완속','공공시설','관공서','서울특별시','중구','서울특별시 중구 세종대로 110(태평로1가, 서울특별시청) 지하2층 24번 기둥','주중 08:00~19:00, 주말 09:00~18:00',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','서울시 본관청사',2,'DC콤보','공공시설','관공서','서울특별시','중구','서울특별시 중구 세종대로 110(태평로1가, 서울특별시청) 지하2층 24번 기둥','주중 08:00~19:00, 주말 09:00~18:00',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','성동구 마장동 거주자우선주차장 가로등형 충전기',1,'DC콤보','기타시설','기타','서울특별시','성동구','서울특별시 성동구 마장동 775-2 트레저힐스(서울특별시 성동구 마조로19길 18 전기차 충전소)','평일 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','성동구청',1,'DC차데모+AC3상+DC콤보','공공시설','관공서','서울특별시','성동구','서울특별시 성동구 고산자로 270(행당동, 성동구청) 지하2층 F7번 구역','주중 08:00~19:00, 주말 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','송월동차고지(완속)',3,'AC완속','관광시설','박물관','서울특별시','종로구','서울특별시 종로구 송월길 52(송월동, 국립기상박물관) 지상1층 주차장 왼쪽 5M(급속), 오른쪽 5M(완속)','주중 08:00~19:00, 주말 09:00~18:00',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','송월동차고지(급속)',2,'DC콤보','관광시설','박물관','서울특별시','종로구','서울특별시 종로구 송월길 52(송월동, 국립기상박물관) 지상1층 주차장 왼쪽 5M(급속), 오른쪽 5M(완속)','주중 08:00~19:00, 주말 09:00~18:00',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','수서역 공영주차장 복합충전소',6,'DC콤보','주차시설','공영주차장','서울특별시','강남구','서울특별시 강남구 광평로47길 28(서울특별시 강남구 광평로 259 전기차충전소)','24시간 이용가능',null,'200kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','양재솔라스테이션',6,'DC차데모+DC콤보','주차시설','일반주차장','서울특별시','서초구','서울특별시 서초구 바우뫼로12길 73(양재동, 양재솔라스테이션) 지상1층 진입로 오른쪽 5M 지점','주중 08:00~19:00, 주말 09:00~18:00',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','양천구청',1,'DC차데모+AC3상+DC콤보','공공시설','관공서','서울특별시','양천구','서울특별시 양천구 목동동로 105전기차충전소','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','어린이대공원 구의문 주차장 복합충전소',6,'DC콤보','주차시설','공영주차장','서울특별시','광진구','서울특별시 광진구 능동로 216(서울특별시 광진구 광나루로 495 전기차충전소)','24시간 이용가능',null,'200kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','어린이대공원 후문주차장',1,'DC콤보','주차시설','공영주차장','서울특별시','광진구','서울특별시 광진구 능동로 216(서울특별시 광진구 천호대로124길 11 전기차충전소)','주중 08:00~19:00, 주말 09:00~18:00',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','으뜸공원 공영주차장 전기차 충전소',1,'AC완속','주차시설','공영주차장','서울특별시','광진구','서울특별시 강북구 솔샘로67길 33으뜸공원 공영주차장(미아동 330-1)','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','자양우성1차아파트 앞 전기차 충전소',1,'DC콤보','주차시설','공영주차장','서울특별시','광진구','서울특별시 광진구 자양번영로 45노상공영주차장 유료 42번(자양동 580-5)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','자양한양아파트 앞 전기차 충전소',1,'DC콤보','주차시설','공영주차장','서울특별시','광진구','서울특별시 광진구 구의강변로 11정문 앞 유료 48번(695 자양한양아파트)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','잠실 청소년센터 앞 전기차 충전소',1,'DC콤보','주차시설','공영주차장','서울특별시','송파구','서울특별시 송파구 올림픽로8길 20잠실 청소년센터(194 잠실아이파크)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','적선동 공영주차장',2,'DC콤보','주차시설','공영주차장','서울특별시','종로구','서울특별시 종로구 새문안로5길 49-1(서울특별시 종로구 새문안로 5길 47 전기차충전소)','주중 08:00~19:00, 주말 09:00~18:00','시설 상황에 따라 이용이 제한될 수 있음','100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','중랑구청',2,'DC콤보','공공시설','관공서','서울특별시','중랑구','서울특별시 중랑구 봉화산로 179(신내동, 중랑구청) 지하1층 19번 기둥','주중 08:00~19:00, 주말 09:00~18:00',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','창동역 공영주차장',1,'DC콤보','주차시설','공영주차장','서울특별시','도봉구','서울특별시 도봉구 마들로11길 74(창동, 창동역공영주차장) 지상1층 진입로 오른쪽 10M','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','천호역 공영주차장',1,'DC차데모+AC3상+DC콤보','주차시설','공영주차장','서울특별시','강동구','서울특별시 강동구 천호대로 지하997(천호동, 천호역공영주차장) 지하1층 A37번 기둥','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','태평로빌딩 앞 생활거점 충전소(완속)',1,'AC완속','주차시설','일반주차장','서울특별시','중구','서울특별시 중구 세종대로 73전기차충전소','24시간 이용가능',null,'7kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','태평로빌딩 앞 생활거점 충전소(급속)',1,'DC콤보','주차시설','일반주차장','서울특별시','중구','서울특별시 중구 세종대로 73전기차충전소','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','홍제1동 공용주차장',2,'DC콤보','주차시설','공영주차장','서울특별시','서대문구','서울특별시 서대문구 홍제내2바길 18(서울특별시 서대문구 홍제내길 58 전기차충전소)','24시간 이용가능',null,'100kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','홍제동 주영빌딩 앞전기차 충전소',1,'DC콤보','주차시설','공영주차장','서울특별시','서대문구','서울특별시 서대문구 홍제내길 128(334-85 주영빌딩)','24시간 이용가능',null,'50kW','N',null);
Insert into CODETRAFFIC.EC_CHARGE (EC_CITY,EC_CHARGE,EC_CHARGE_ID,EC_CHARGE_TYPE,EC_CHARGE_FACILITY,EC_CHARGE_PARKING,EC_LOCATION,EC_STATE,EC_ADDRESS,EC_TIME,EC_USER,EC_KW,EC_FACILITY2,EC_NOTE) values ('서울시','화창운수 앞 가로등형 충전소',1,'DC콤보','주차시설','공영주차장','서울특별시','마포구','서울특별시 마포구 토정로 272전기차충전소','주중 08:00~19:00, 주말 09:00~18:00',null,'50kW','N',null);
